### ISSUE TITLE
Broken with snowpack v1.2

### ISSUE THREAD

**Issue by jakedeichert** [jakedeichert/svelvet#37]
Just noticed this error today when doing a clean install which comes with latest snowpack, v1.2.0.

```
Failed to transform with babel: dist/pages/Home.js
Error: unknown: Import map not found. Run Snowpack first to generate one.
  ✘ /path/to/MY_PROJECT/web_modules/import-map.local.json
  ✘ /path/to/MY_PROJECT/web_modules/import-map.json
    at readImportMapFile (/path/to/MY_PROJECT/node_modules/snowpack/assets/babel-plugin.js:21:9)
    at getImportMap (/path/to/MY_PROJECT/node_modules/snowpack/assets/babel-plugin.js:27:24)
    at PluginPass.pre (/path/to/MY_PROJECT/node_modules/snowpack/assets/babel-plugin.js:83:28)
    at transformFile (/path/to/MY_PROJECT/node_modules/@babel/core/lib/transformation/index.js:96:27)
    at transformFile.next (<anonymous>)
    at run (/path/to/MY_PROJECT/node_modules/@babel/core/lib/transformation/index.js:35:12)
    at run.next (<anonymous>)
    at Object.transform (/path/to/MY_PROJECT/node_modules/@babel/core/lib/transform.js:27:41)
    at transform.next (<anonymous>)
    at step (/path/to/MY_PROJECT/node_modules/gensync/index.js:254:32) {
  code: 'BABEL_TRANSFORM_ERROR'
}
```

**Comment by jakedeichert** [comment]
Should lock down the version of snowpack used to prevent breakages like this...

**Comment by YogliB** [comment]
This is still an issue for me.

When I run `npm run dev` , `node_modules\snowpack\dist-node\index.bin.js` is being opened, and when I close it I get the `babel` errors.

**Comment by jakedeichert** [comment]
Hmm... I wasn't getting any errors after this fix.

Are you getting the exact same error as I posted? If so, can you copy paste the output here. `index.bin.js` is not in my error so I'm not sure it's the same as what you're getting.

If you notice it is a different error, please open a new issue and provide more details. Svelte version, svelvet version, node version, npm version would be helpful.

@YogliB
