### ISSUE TITLE
Svelvet (re-)compiling to src/ instead of dist/ on Windows, triggering babel parse errors

### ISSUE THREAD

**Issue by moitias** [jakedeichert/svelvet#43]
So, for some reason, running svelvet on windows causes the hot-reload triggered and re-compiled files to appear in src/[file].js rather than dist/[file.js]. This has the immediate effect of hot reload not working and the follow-up effect of creating extra (babelized/compiled) copies of the same file in .src that in turn get re-babelized again, it seems. 

This results in various errors, but the most common ones I've seen are:
`Cannot find module 'svelte/internal.js'` 
or
```
Failed to transform with babel: src\App.js
{ SyntaxError: unknown: Unterminated string constant (87:23)

  85 | }
  86 |
> 87 | export default App;nent", {
     |                        ^
  88 |       component: this,
  89 |       tagName: "App",
  90 |       options,
    at Parser.raise (...\node_modules\@babel\parser\lib\index.js:7017:17)
    at Parser.readString (...\node_modules\@babel\parser\lib\index.js:8010:20)
    at Parser.getTokenFromCode (...\node_modules\@babel\parser\lib\index.js:7664:14)
    at Parser.nextToken (...\node_modules\@babel\parser\lib\index.js:7241:12)
    at Parser.next (...\node_modules\@babel\parser\lib\index.js:7170:10)
    at Parser.parseIdentifierName (...\node_modules\@babel\parser\lib\index.js:10366:10)
    at Parser.parseIdentifier (...\node_modules\@babel\parser\lib\index.js:10335:23)
    at Parser.parseExprAtom (...\node_modules\@babel\parser\lib\index.js:9516:27)
    at Parser.parseExprSubscripts (...\node_modules\@babel\parser\lib\index.js:9259:23)
    at Parser.parseMaybeUnary (...\node_modules\@babel\parser\lib\index.js:9239:21)
  pos: 1796,
  loc: Position { line: 87, column: 23 },
  code: 'BABEL_PARSE_ERROR' }
```

(note that it looks like the end of the file just repeats - I'm guessing this is due to the src/App.js being babelized over the babelized src/App.svelte in dist/App.js or the other way around? eg. we're seeing the most of one file and the end of another file there?)

Steps basically are;
1. Have no dist/ and just App.svelte and index.html in src/
2. run svelvet, everything compiles to dist properly and dev server is started up;
```
$ svelvet
(node:15176) ExperimentalWarning: The fs.promises API is experimental
Copied asset dist/index.html
Svelte compiled dist/components/Header.js
Svelte compiled dist/App.js

Building web_modules with snowpack...
- snowpack installing...
√ snowpack installed: svelte/internal. [0.31s]

Babel transformed dist/components/Header.js
Babel transformed dist/App.js
Watching for files...
Server running on http://localhost:8080
```
3. edit App.svelte, log shows a lot of compilation happening (note src instead of dist);
```
Svelte compiled src\App.js
Babel transformed src\App.js
Svelte compiled src\App.js
Svelte compiled src\App.js
Babel transformed src\App.js
Babel transformed src\App.js
Svelte compiled src\App.js
Svelte compiled src\App.js
Babel transformed src\App.js
Babel transformed src\App.js
Svelte compiled src\App.js
Babel transformed src\App.js
Svelte compiled src\App.js
Babel transformed src\App.js
Svelte compiled src\App.js
Babel transformed src\App.js
```
4. no hot reload is seen, nothing is reloaded. src/App.js is created, containing the *new* compiled version
5. edit App.svelte again
6. babel compilation errors appear, subsequent log is as follows:
```
Svelte compiled src\App.js
Svelte compiled src\App.js
Babel transformed src\App.js

Failed to transform with babel: src\App.js
{ SyntaxError: unknown: Unterminated string constant (87:23)

  85 | }
  86 |
> 87 | export default App;nent", {
     |                        ^
  88 |       component: this,
  89 |       tagName: "App",
  90 |       options,
    at Parser.raise (...\node_modules\@babel\parser\lib\index.js:7017:17)
    at Parser.readString (...\node_modules\@babel\parser\lib\index.js:8010:20)
    at Parser.getTokenFromCode (...\node_modules\@babel\parser\lib\index.js:7664:14)
    at Parser.nextToken (...\node_modules\@babel\parser\lib\index.js:7241:12)
    at Parser.next (...\node_modules\@babel\parser\lib\index.js:7170:10)
    at Parser.parseIdentifierName (...\node_modules\@babel\parser\lib\index.js:10366:10)
    at Parser.parseIdentifier (...\node_modules\@babel\parser\lib\index.js:10335:23)
    at Parser.parseExprAtom (...\node_modules\@babel\parser\lib\index.js:9516:27)
    at Parser.parseExprSubscripts (...\node_modules\@babel\parser\lib\index.js:9259:23)
    at Parser.parseMaybeUnary (...\node_modules\@babel\parser\lib\index.js:9239:21)
  pos: 1802,
  loc: Position { line: 87, column: 23 },
  code: 'BABEL_PARSE_ERROR' }

Svelte compiled src\App.js

Failed to transform with babel: src\App.js
{ SyntaxError: unknown: Unterminated string constant (87:23)

  85 | }
  86 |
> 87 | export default App;nent", {
     |                        ^
  88 |       component: this,
  89 |       tagName: "App",
  90 |       options,
    at Parser.raise (...\node_modules\@babel\parser\lib\index.js:7017:17)
    at Parser.readString (...\node_modules\@babel\parser\lib\index.js:8010:20)
    at Parser.getTokenFromCode (...\node_modules\@babel\parser\lib\index.js:7664:14)
    at Parser.nextToken (...\node_modules\@babel\parser\lib\index.js:7241:12)
    at Parser.next (...\node_modules\@babel\parser\lib\index.js:7170:10)
    at Parser.parseIdentifierName (...\node_modules\@babel\parser\lib\index.js:10366:10)
    at Parser.parseIdentifier (...\node_modules\@babel\parser\lib\index.js:10335:23)
    at Parser.parseExprAtom (...\node_modules\@babel\parser\lib\index.js:9516:27)
    at Parser.parseExprSubscripts (...\node_modules\@babel\parser\lib\index.js:9259:23)
    at Parser.parseMaybeUnary (...\node_modules\@babel\parser\lib\index.js:9239:21)
  pos: 1802,
  loc: Position { line: 87, column: 23 },
  code: 'BABEL_PARSE_ERROR' }

Svelte compiled src\App.js
Svelte compiled src\App.js

Failed to transform with babel: src\App.js
{ SyntaxError: unknown: Unterminated string constant (87:23)

  85 | }
  86 |
> 87 | export default App;nent", {
     |                        ^
  88 |       component: this,
  89 |       tagName: "App",
  90 |       options,
    at Parser.raise (...\node_modules\@babel\parser\lib\index.js:7017:17)
    at Parser.readString (...\node_modules\@babel\parser\lib\index.js:8010:20)
    at Parser.getTokenFromCode (...\node_modules\@babel\parser\lib\index.js:7664:14)
    at Parser.nextToken (...\node_modules\@babel\parser\lib\index.js:7241:12)
    at Parser.next (...\node_modules\@babel\parser\lib\index.js:7170:10)
    at Parser.parseIdentifierName (...\node_modules\@babel\parser\lib\index.js:10366:10)
    at Parser.parseIdentifier (...\node_modules\@babel\parser\lib\index.js:10335:23)
    at Parser.parseExprAtom (...\node_modules\@babel\parser\lib\index.js:9516:27)
    at Parser.parseExprSubscripts (...\node_modules\@babel\parser\lib\index.js:9259:23)
    at Parser.parseMaybeUnary (...\node_modules\@babel\parser\lib\index.js:9239:21)
  pos: 1802,
  loc: Position { line: 87, column: 23 },
  code: 'BABEL_PARSE_ERROR' }


Failed to transform with babel: src\App.js
{ SyntaxError: unknown: Unterminated string constant (87:23)

  85 | }
  86 |
> 87 | export default App;nent", {
     |                        ^
  88 |       component: this,
  89 |       tagName: "App",
  90 |       options,
    at Parser.raise (...\node_modules\@babel\parser\lib\index.js:7017:17)
    at Parser.readString (...\node_modules\@babel\parser\lib\index.js:8010:20)
    at Parser.getTokenFromCode (...\node_modules\@babel\parser\lib\index.js:7664:14)
    at Parser.nextToken (...\node_modules\@babel\parser\lib\index.js:7241:12)
    at Parser.next (...\node_modules\@babel\parser\lib\index.js:7170:10)
    at Parser.parseIdentifierName (...\node_modules\@babel\parser\lib\index.js:10366:10)
    at Parser.parseIdentifier (...\node_modules\@babel\parser\lib\index.js:10335:23)
    at Parser.parseExprAtom (...\node_modules\@babel\parser\lib\index.js:9516:27)
    at Parser.parseExprSubscripts (...\node_modules\@babel\parser\lib\index.js:9259:23)
    at Parser.parseMaybeUnary (...\node_modules\@babel\parser\lib\index.js:9239:21)
  pos: 1802,
  loc: Position { line: 87, column: 23 },
  code: 'BABEL_PARSE_ERROR' }
```

Will probably be investigating further and happy to help out in debugging - I'm rather excited about the project and idea!

**Comment by moitias** [comment]
Tracked this down to the destPath logic in `compile()` not taking into account the different path separators on Windows / POSIX. 

Not exactly sure what the idiomatic way of solving this, but something like 
```
        const destPath = srcPath
            .replace(new RegExp(`^src\\${path.sep}`, `dist${ path.sep}`)
            .replace(/.svelte$/, '.js');
```
should work? Happy to create a PR with the above if it sounds good.

**Comment by jakedeichert** [comment]
Thanks for the very detailed report! :)

I'll give your solution a try and see how it goes! If it works locally for me still, I'll PR and release tonight with the other windows bug fix you made 👍

**Comment by jakedeichert** [comment]
Released as [v0.3.1](https://github.com/jakedeichert/svelvet/releases/tag/v0.3.1)! Thanks for the help 👍

**Comment by moitias** [comment]
My pleasure, although looks like I forgot to actually create a PR for this fix; but I also wasn't 100% on whether it was the right/idiomatic solution for this nor could not run the tests (as tests rely on bash).

I'll probably be playing with svelvet over the weekend; how would you feel about me taking a stab at turning test.sh into equivalent JS script in order to lose the dependency on bash?

**Comment by jakedeichert** [comment]
@moitias the test script just cd's into some snapshot dirs, npm installs and runs npm run build. If you have WSL, I think the bash script might work?

Re: converting to a js script, that can get a bit ugly integrating and calling shell cmds (done it a few times 😅). I'd be more open to the possibility of making a second test script for Windows.. powershell or something? I'm not very up to date on windows shell scripting :)

If we had a windows-based script, then we could also get github ci running tests under windows too!
