### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by niczero** [jakedeichert/svelvet#51]
When I go into the `basic` directory, and try to build:

```sh
npm i
npm run dev
```

I get the following error (identical problem when doing `npm run build`).

```sh
(4)basic $ npm run dev

> svelvet-example-basic@ dev /.../svelvet/examples/basic
> svelvet

(node:16287) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'mkdir' of undefined
    at copyFile (/.../svelvet/examples/basic/node_modules/svelvet/lib/index.js:87:25)
    at concurrencyLimit (/.../svelvet/examples/basic/node_modules/svelvet/lib/index.js:155:83)
    at resolve (/.../svelvet/examples/basic/node_modules/p-try/index.js:4:10)
    at new Promise (<anonymous>)
    at pTry (/.../svelvet/examples/basic/node_modules/p-try/index.js:3:37)
    at run (/.../svelvet/examples/basic/node_modules/p-limit/index.js:23:18)
    at enqueue (/.../svelvet/examples/basic/node_modules/p-limit/index.js:32:4)
    at resolve (/.../svelvet/examples/basic/node_modules/p-limit/index.js:38:60)
    at new Promise (<anonymous>)
    at generator (/.../svelvet/examples/basic/node_modules/p-limit/index.js:38:37)
(node:16287) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:16287) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is with v0.3.0 on node v8.10.0 on linux.

**Comment by niczero** [comment]
I upgraded to v0.3.2 by doing

```sh
npm i
npm i -D ../../
npm run dev
```

but that gives the same error.

**Comment by jakedeichert** [comment]
Node v10 is required for svelvet to run 👍

**Comment by niczero** [comment]
yes, was just returning to report that I'd just seen the message saying 'node 10 is recommended'.  I upgraded to node 12 and things are working.
If it doesn't work with node <10 then it would really help to have an error or something more emphatic and noticeable rather than a 'recommended'.
